### ISSUE TITLE
Unwanted ssh key in provisionning

### ISSUE THREAD

**Issue by CyrilleHugues** [MaximeThoonsen/ansible-devops#1]
Hi, 

I installed your ansible provisionning recently and came across your ssh key in the webserver authorized_keys file.
Would you mind to remove it ?

Greets,
Cyrille

**Comment by MaximeThoonsen** [comment]
Hello @CyrilleHugues ,

This provisioning is deprecated, you should use the new one: https://github.com/MaximeThoonsen/symfony-ansible

But thanks for the review anyway ;)

Maxime
